### PR TITLE
added gcm

### PR DESCRIPTION
**Pull request by danlapid**
Tests are passing of course

### CODE REVIEW

**Review by Blank-c — APPROVED** [review]
GCM Working!

**Comment by Blank-c** [comment]
But I think the repo is dead??

**Comment by ricmoo** [comment]
Sorry, I haven’t been very attentive at updating this repo or the related package. I should look for a co-maintainer at the very least that actively works with Python.

I was actually hoping that by now AES would be an important enough primitive it would be part of the python standard library by now, but it sounds like that isn’t the case?

**Comment by Blank-c** [comment]
thats sad but this library has an advantage over the popular library "pycryptodome". This library mainly focus on AES and is therefore small and lightweight. I would really like if you keep this up!

**Comment by uzlonewolf** [comment]
While it's a good start, this PR breaks when passed IVs >96 bits and also does not handle authentication tags at all (which are the whole point of GCM mode).

**Comment by tomtyiu** [comment]
please help me fix it

**Pull request closed without merging**
